#!/usr/bin/env python

import re
import subprocess

HEADER="""
<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title data-localize="title">CyanogenMod Directory Index - HUST Open Source Mirrors</title>
		<link href="/assets/css/bootstrap.min.css" rel="stylesheet"/>
		<style type="text/css">
			html,
			body {
				height: 100%;
			}
			.container,
			.navbar-fixed-top .container{
				width: 80%;
			}
			.container .credit {
				margin: 13px 0;
			}
			.centerblock {
				text-align: center;
			}
			#wrap {
				min-height: 100%;
				height: auto !important;
				height: 100%;
				margin: 0 auto -80px;
			}
			#push,
			#footer {
				height: 80px;
			}
			#footer {
				background-color: #f5f5f5;
			}
			#wrap > .container {
				padding-top: 60px;
			}
		</style>
	</head>
	<body>
		<div id="wrap">
			<div class="navbar navbar-fixed-top navbar-inverse">
				<div class="navbar-inner">
					<div class="container">
						<a class="brand" href="/" data-localize="main-name">HUST Open Source Mirrors</a>
						<ul class="nav">
							<li><a href="/" data-localize="nav.home">Home</a></li>
							<li><a href="/help" data-localize="nav.help">Help</a></li>
							<li><a href="/graph" data-localize="nav.graph">Graph</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="centerblock">
					<h1 data-localize="title">CyanogenMod Directory Index</h1>
					<p class="lead">Tip: Use Ctrl-F to search for your device.</p>
"""
TABLE_HEADER="""
					<table class="table">
						<tr><th>Build type</th><th>File name</th><th>CM Version</th><th>Device codename</th></tr>
"""
TABLE_FOOTER = """
					</table>"""

FOOTER="""
				</div>
			</div>
			<div id="push"></div>
		</div>
		<div id="footer">
			<div class="container centerblock">
				<p class="muted credit" data-localize="credit">This site is brought to you by <a href="http://qiming.hust.edu.cn/" target="qiming">Qiming College, HUST</a> and <a href="http://www.hustunique.com/" target="_blank">Unique Studio</a>.</p>
				<p class="muted credit" data-localize="contact">Contact us at <a href="http://www.google.com/recaptcha/mailhide/d?k=01h7Er0RVnO4wvIFgIk2lR-g==&c=-7_mZ8fYpJyWgM9qxj57zKaij5zJpRkBUBNpq2619zs=" target="_blank" onclick="window.open('http://www.google.com/recaptcha/mailhide/d?k=01h7Er0RVnO4wvIFgIk2lR-g==&c=-7_mZ8fYpJyWgM9qxj57zKaij5zJpRkBUBNpq2619zs=', '', 'toolbar=0,scroolbars=0,location=0,menubar=0,resizable=0,width=500,height=300');return false;">our email address</a></p>
			</div>
		</div>
		<script src="/assets/js/jquery.min.js" type="text/javascript"></script>
		<script src="/assets/js/jquery.localize.js" type="text/javascript"></script>
		<script type="text/javascript">
		l10nopts = {
			skipLanguage: ["en", "en-US"],
			pathPrefix: "/l10n"
		};
		$('[data-localize]').localize('cmindex', l10nopts);
		</script>
	</body>
</html>
<!-- Written by Qijiang Fan and Haochen Tong in Vim -->
<!-- IT Service Team @ Unique Studio -->
"""

CMROOT="/home/mirror/mirrordata/cm/"

def parse_filename(f):
    info = {'cmver': '???', 'device': '???', 'name':'', 'path':'', 'type': 'Stable', 'changelog': ''}
    r = f.split('/')[-1][:-4]
    d = r
    if r.endswith('-signed'):
        r = r[:-7]
    if r.startswith('update-'):
        r = r[7:]
    info['path'] = f
    info['name'] = d
    info['changelog'] = '/'.join(f.split('/')[:-1]) + "/CHANGES.txt"
    fields = r.split('-')[1:]
    for i in range(len(fields)):
        if i == 0:
            info['cmver'] = fields[i]
        elif i == 1:
            if re.match(r"\d{8}", fields[i]):
                continue
            elif re.match(r"RC\d+", fields[i]):
                info['cmver'] += '-' + fields[i]
                info['type'] = "RC"
            else:
                info['device'] = fields[i]
        elif i == 2:
            if fields[i] == "NIGHTLY" or fields[i] == "SNAPSHOT":
                info['type'] = "Nightly"
            elif fields[i] == "EXPERIMENTAL":
                info['type'] = "Experimental"
            else:
                info['device'] = fields[i]
        elif i == 3:
            info['device'] = fields[i]
        else:
            break  # stop searching

    return info


def generate_most_recent(files, count):
    output = open(CMROOT + "index.html", "w")
    output.write(HEADER)
    output.write('<p class="lead">Only the most recent 60 builds are shown. See <a href="all.html">full list</a> here.</p>\n')
    output.write(TABLE_HEADER)
    i = 0
    for f in files:
        if i > count:
            break
        info = parse_filename(f)
        output.write('<tr><td>%s</td><td><a href="/cm%s">%s</a> (<a href="/cm%s">ChangeLog</a>)</td><td>%s</td><td>%s</td></tr>\n' %
                (info['type'], info['path'], info['name'], info['changelog'], info['cmver'], info['device']))
        i += 1

    output.write(TABLE_FOOTER + FOOTER)
    output.close()


def generate_directory_index(files):
    output = open(CMROOT + "all.html", "w")
    output.write(HEADER + TABLE_HEADER)
    result = subprocess.check_output(r"find " + CMROOT + " -name '*.zip' -type f -printf '%T@ %p\n' | sort -k 1nr | sed -e 's/^[^ ]* //' -e 's#" + CMROOT + "##'", shell=True)
    for f in files:
        info = parse_filename(f)
        output.write('<tr><td>%s</td><td><a href="/cm%s">%s</a></td><td>%s</td><td>%s</td></tr>\n' %
                (info['type'], info['path'], info['name'], info['cmver'], info['device']))

    output.write(TABLE_FOOTER + FOOTER)
    output.close()

if __name__ == '__main__':
    cmd = r"find %s/jenkins %s/jenkins-test -name '*.zip' -type f -printf '%%T@ %%p\n' | sort -k 1nr | sed -e 's/^[^ ]* //' -e 's#%s##'" % (CMROOT, CMROOT, CMROOT)
    result = subprocess.check_output(cmd, shell=True)
    files = result.strip().split('\n')
    generate_most_recent(files, 60)
    generate_directory_index(files)
