#!/bin/bash

cd $(dirname $0)
export CWD=$(pwd)
export MIRRORROOT=/home/mirror/mirrordata
export LOGROOT=/home/mirror/mirrorlog
export STATUSROOT=/home/mirror/mirrorweb/status/
export SCRIPTROOT=/home/mirror/scripts

NOW=$(date +%s)
NEXT=$(cat "$STATUSROOT/$1.json" | python -c 'import json;p=json.loads(raw_input());print "lastsync" in p and p["nextsync"] or -1')
if [ "${NEXT}1" -gt "${NOW}1" ]; then
	WAIT=$((NEXT-NOW))
	sleep $WAIT
fi

while true; do
    ./sync_core $1 >/dev/null 2>/dev/null
    NEXTSYNC=$(cat "$STATUSROOT/$1.json" | python -c 'import json;p=json.loads(raw_input());print "lastsync" in p and p["nextsync"] or -1')
    NOW=`date +%s`
    SLEEPTIME=$((NEXTSYNC-NOW))
    if [ "$SLEEPTIME" -le "0" ]; then
        continue
    else
        sleep "$SLEEPTIME"
    fi
done
