#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=cm
_UPSTREAM=rsync://download.cyanogenmod.org/mirror/
_SYNCEVERY=7200
_FAILRETRY=600
_FAILRETRIES=4

_post_sync() {
    $SCRIPTROOT/cm_dir_index
}
