#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=cm
_UPSTREAM=rsync://download.cyanogenmod.org/mirror/
_SYNCEVERY=9600
_FAILRETRY=900
_FAILRETRIES=4
_RSYNC_ARGS="$_RSYNC_ARGS --exclude index.html --exclude all.html"

_post_sync() {
    $SCRIPTROOT/cm_dir_index
}

_upstream_inconsistent() {
    curl -s "http://jenkins.cyanogenmod.org/job/android/lastBuild/api/json?tree=building" | python -c 'import sys,json; exit(int(not json.load(sys.stdin)["building"]))'
}
