#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=gentoo-portage
_UPSTREAM=rsync://rsync.us.gentoo.org/$_REPO/
_SYNCEVERY=600
_FAILRETRY=600
_FAILRETRIES=4
_TIMESTAMP_PATHS="/metadata/timestamp.chk"
