#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=kali-images
_UPSTREAM=rsync://kali.mirror.garr.it/$_REPO/
_SYNCEVERY=3600
_FAILRETRY=600
_FAILRETRIES=4
_TIMESTAMP_PATHS="/kali-latest/amd64/SHA1SUMS"
