#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=kali
_UPSTREAM=rsync://kali.mirror.garr.it/$_REPO/
_SYNCEVERY=600
_FAILRETRY=600
_FAILRETRIES=4
_UPSTREAM_HTTP=http://kali.mirror.garr.it/mirrors/kali
_TIMESTAMP_PATHS="/project/trace/mirror3.mirror.garr.it"
