#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=mariadb
_UPSTREAM=rsync://rsync.osuosl.org/$_REPO/
_SYNCEVERY=600
_FAILRETRY=600
_FAILRETRIES=4
_RSYNC_ARGS="$_RSYNC_ARGS --partial"
_TIMESTAMP_PATHS="/TIME"
