#!/bin/bash

source $SCRIPTROOT/syncbin/.rsync_base

_REPO=sagemath
_UPSTREAM=rsync://boxen.math.washington.edu/sage/
_SYNCEVERY=600
_FAILRETRY=600
_FAILRETRIES=4
_TIMESTAMP_PATH="/zzz/timestamp.html"
